import { test, expect, eventHeaders } from '../../helpers/event-fixture';
import { storyImageFixture } from '../../helpers/story-image';
test('E2E-WEB-1142 reviewed generated bytes display with truthful label on reader @STORY-MEDIA-002 @TEST-SIMULATION', async ({
  page,
  request,
  feedbackSandbox,
}) => {
  const f = await storyImageFixture(request, feedbackSandbox);
  await request.put('/api/v1/ops/media/' + f.source.id, {
    headers: eventHeaders,
    data: { assetId: f.asset.id, imageAttemptId: f.attemptId, publish: true },
  });
  await page.route('**/api/v1/discovery/items/**', (route) => {
    const url = new URL(route.request().url());
    return route.continue({
      url: feedbackSandbox.apiOrigin + url.pathname + url.search,
    });
  });
  await page.goto('/#read/' + f.source.id);
  const region = page.getByRole('region', { name: 'Reviewed visual summary' });
  await expect(region.locator('img')).toHaveAttribute(
    'src',
    /^data:image\/png;base64,/,
  );
  await expect(region).toContainText('AI-generated conceptual illustration');
});
test('E2E-WEB-1143 gesture guidance dismisses once per document with reduced motion @STORY-MEDIA-002', async ({
  page,
}) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/#today');
  await page.getByRole('button', { name: 'Stories', exact: true }).click();
  const hint = page.getByRole('note', { name: 'Reading gesture guide' });
  await expect(hint).toBeVisible();
  await expect(hint.locator('.gesture-demo')).toHaveCSS(
    'animation-name',
    'none',
  );
  await hint.getByRole('button', { name: 'Got it' }).click();
  await expect(hint).toHaveCount(0);
  const story = page.getByRole('region', { name: 'Reading story' });
  await expect(story.locator('.story-glyph')).toHaveCount(0);
  await story.focus();
  await page.keyboard.press('ArrowDown');
  await expect(hint).toHaveCount(0);
});
